### ISSUE TITLE
drop vscodium

### ISSUE THREAD

**Issue by 13werwolf13** [openSUSE/opi#127]
vscodium rpm repo is dead

**Comment by heldiho53** [comment]
@13werwolf13 
Sorry but what are you talking about? It's right here: 
https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo

**Comment by 13werwolf13** [comment]
> @13werwolf13 
> Sorry but what are you talking about? It's right here: 
> https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo

This is a dead repository, it will no longer be possible to use it. The main url of the repository gives 404. And the certificate is rotten on the mirror.

**Comment by heldiho53** [comment]
> > @13werwolf13
> > Sorry but what are you talking about? It's right here:
> > https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo
> 
> This is a dead repository, it will no longer be possible to use it. The main url of the repository gives 404. And the certificate is rotten on the mirror.

But it is still usable? I just installed vscodium from exactly that repo with opi?

**Comment by asdil12** [comment]
hm - https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/ doesn't 404 for me.
Is there some better information source you can provice, @13werwolf13 ?

**Comment by 13werwolf13** [comment]
> hm - https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/ doesn't 404 for me.
> Is there some better information source you can provice, @13werwolf13 ?

I apologize. The repository gave me 404 for more than a month, the problem was observed from different providers and I decided that it was dead. But now it works. I don't know if there were problems with the repository or with my providers, but the problem is gone. The issue can be closed.
