### ISSUE TITLE
What is the minimum python version required?

### ISSUE THREAD

**Issue by ecsgh** [openSUSE/opi#147]
I can't find a definition of this in the sources.
And the built version in utilities for 15.5 does not work.

**Comment by nobkd** [comment]
Just, if it helps, the [tests use the `python3` package](https://github.com/openSUSE/opi/blob/master/test/run_container_test.sh#L12)

**Comment by ecsgh** [comment]
Unfortunately not really.
Because Python stands in Leap, if I know it correctly, for python 3.6 and inTumbleweed for Python 3.10 or 3.11.

**Comment by asdil12** [comment]
hm - in which way does it 'not work'?

I can't actually reproduce the issue:
```
podman run -it --rm opensuse/leap:15.5
zypper in opi
opi --version
# use opi to install opi from utilities repo
opi opi
opi --version
# python3 --version
Python 3.6.15
```

**Comment by ecsgh** [comment]
opi --version still works without errors.
But if you search for a package the error appears.

And why is it so hard to say which is the minimum required Python version?

**Comment by nobkd** [comment]
Are you running opi with sudo?

Are you able to provide the error log?

Because as far as I see theoretically all python 3 versions should work.

**Comment by ecsgh** [comment]
opi firefox
Pick a number (0 to quit): 1
You have selected package name: MozillaFirefox
Traceback (most recent call last):
  File "/usr/bin/opi", line 92, in <module>
    binaries = opi.search_local_repos(selected_name) + binaries
  File "/usr/lib/python3.6/site-packages/opi/__init__.py", line 165, in search_local_repos
    installable['repository'] = repos_by_name[repo_name]
KeyError: 'repositories:mozilla 15.5'

**Comment by asdil12** [comment]
> And why is it so hard to say which is the minimum required Python version?

I actually don't know exactly. I simply run the testsuite for latest leap and tumbleweed.
As it passes for Leap15.5 shipping python3.6, I would expect it to work for python >=3.6.

**Comment by asdil12** [comment]
The stack trace indicates that this is not an issue with the python version but there seems to be a bug in opi (>=3.x.x I guess) that is triggered by a repo that is enabled on your local system.
Could you send me the output of `zypper lr -u` as well as the content of the `.repo` file (in `/etc/zypp/repos.d`) for the repo that this error refers to (`'repositories:mozilla 15.5'` - I guess the file has `mozilla` in its name).

**Comment by ecsgh** [comment]
zypper lr:
Alias                                           | Name
...
repositories_mozilla               | repositories:mozilla 15.5  

Content of mozilla.repo:
[repositories_mozilla]
name=repositories:mozilla $releasever
enabled=1
autorefresh=1
baseurl=https://download.opensuse.org/repositories/mozilla/openSUSE_Leap_$releasever/
path=/
type=rpm-md
keeppackages=0

But one more note.
This is not the only repo where the error occurs.

**Comment by asdil12** [comment]
I can reproduce the issue.
I'm pretty sure that the `$releasever` in the `name` field is what opi can't deal with at the moment.

**Comment by asdil12** [comment]
Yes - that is because with opi 3 the local repos will be searched as well.
opi version 2 doesn't have this feature yet.

**Comment by ecsgh** [comment]
Ah okay.
With your change es patch for 3.4.0 opi runs without error.
Thank you.
