### ISSUE TITLE
Add option to ignore third-party repos

### ISSUE THREAD

**Issue by draskmont** [openSUSE/opi#149]
Currently, if the start of your query matches one of the command options to install third-party repositories, your only options are to either install the repo or drop the operation entirely. 
Something like `opi dotnet-sdk` still triggers the prompt, making trimming letters the only option if you want to search the obs

This could be solved by adding a flag to signal that you only want to search in the OBS or maybe make opi carry out the search if the user rejects the first prompt

**Comment by nobkd** [comment]
`dotnet-sdk` is in the queries list and therefore is chosen (not because it starts with `dotnet`):
https://github.com/openSUSE/opi/blob/1a24e77ebd776c15a098a9d43291653a7bfb0be7/opi/plugins/dotnet.py#L7

---

The option is probably still a good idea.
