### ISSUE TITLE
DNF5 Backend?

### ISSUE THREAD

**Issue by Rerum02** [openSUSE/opi#170]
Was wondering if I could beta test to see how well [DNF5](https://build.opensuse.org/package/show/system:packagemanager:dnf/dnf5) worked. Probably wont end well, but would love to test it out.

**Comment by asdil12** [comment]
Feel free to test - but even the dnf4 backend is not really in a good state I guess.
It was contributed by someone else, but there are not really any tests for it, so I guess it is broken.
Also some options do not exist for dnf.
