### ISSUE TITLE
[Bug] Wrong priority for Packman repo added by OPI on openSUSE Slowroll

### ISSUE THREAD

**Issue by Xathros1** [openSUSE/opi#180]
### Bug Report Description
**Issue:**
When using OPI to add the Packman repository to openSUSE Slowroll, it assigns a priority of 90. This configuration can cause potential conflicts since the `update-slowroll` repository is assigned a priority of 80 by default when using the zypp services if the `openSUSE-repos-Slowroll` package is installed.

**Steps to Reproduce:**
1. Install OPI on openSUSE Slowroll.
2. Add the Packman repository with OPI.
3. Check the priority assigned to the Packman repository.

**Expected Behavior:**
The Packman repository should be added with a priority of 70, as suggested by the official [openSUSE Slowroll documentation](https://en.opensuse.org/openSUSE:Slowroll).

**Actual Behavior:**
The Packman repository is added with a priority of 90, which is lower than the `update-slowroll` repository's priority of 80, leading to potential update conflicts.

**Proposed Solution:**
Modify OPI to add the Packman repository with a priority of 70 to match the recommendations on the openSUSE site.

**Additional Information:**
- openSUSE version: openSUSE Tumbleweed-Slowroll VERSION="20240429"
- OPI version: opi version 5.0.0
- Zypp services and repository management tool used: openSUSE-repos-Slowroll

**Comment by asdil12** [comment]
https://build.opensuse.org/request/show/1179230
