### ISSUE TITLE
reverse results 

### ISSUE THREAD

**Issue by ItsNilDev** [openSUSE/opi#57]
wouldn't implementing a reverse result be good ? for example when you search for `i3` it shows over 580+ results and you have to grab the mouse and go all the way up...
I think we should have something like arch's `yay` which makes it really easy to grab the result you want.
I know we can use regexes like `i3*` and ` | less`...

**Comment by trmdi** [comment]
Similar issue: https://github.com/openSUSE/opi/issues/56

**Comment by ItsNilDev** [comment]
Similar, but not what I'm trying to do here

**Comment by Zhongrui-Cao** [comment]
Do you simply mean we should make the first results printed last? or something similar to `yay --bottomup`  `yay --topdown`

**Comment by Zhongrui-Cao** [comment]
> Similar, but not what I'm trying to do here

Do you simply mean we should make the first results printed last? or something similar to yay --bottomup yay --topdown?
