### ISSUE TITLE
command arguments not recognised

### ISSUE THREAD

**Issue by jack-sprat** [openSUSE/opi#91]
## v2.4.4 on opensuse 15.3:

> if I try to use any of the command arguments (-h, -v, -r), opi appears to search for them, forever, and eventually I have to break with CTRL-C

```
> opi -h
Searching...
^C
```

**Comment by asdil12** [comment]
I think in 15.3 there is still the old perl version of opi.
What does `rpm -qi opi` say?

**Comment by jack-sprat** [comment]
Name        : opi
Version     : 0.8.2
Release     : bp153.1.14
Architecture: noarch
Install Date: Sat 26 Feb 2022 21:19:45 GMT
Group       : System/Packages
Size        : 167700
License     : GPL-3.0-only
Signature   : RSA/SHA256, Sat 06 Mar 2021 02:35:09 GMT, Key ID 9c214d4065176565
Source RPM  : opi-0.8.2-bp153.1.14.src.rpm
Build Date  : Sat 06 Mar 2021 02:34:54 GMT
Build Host  : lamb61
Relocations : (not relocatable)
Packager    : https://bugs.opensuse.org
Vendor      : openSUSE
URL         : https://github.com/openSUSE-zh/opi
Summary     : OBS Package Installer (CLI)
Description :
OBS Package Installer (CLI)
Distribution: SUSE Linux Enterprise 15 SP3

**Comment by asdil12** [comment]
Yeah - that is the old version - the new python rewrite will be included in 15.4.
You can however use `opi` to install the current version of `opi` from the `utilities` repo:
```
$ opi opi

**Comment by jack-sprat** [comment]
ahh.. okay, thanks - I'll note that on OS forum thread: https://forums.opensuse.org/showthread.php/566428-LEAP-15-3-not-so-well-supported-eh
